### ISSUE TITLE
Some Notes

### ISSUE THREAD

**Issue by bms63** [pharmaverse/rpharma-2024-ADaM-workshop#1]
#  Pre-requisites for Workshop

## Installing Packages Best Practices
* Always update to the latest packages - Select All and update
* We probably won't run into this with the container - but if we do

## Slack Channel
* Encourage attendees join the slack channel - 
* Not a cure-all, but what we got!  

## Workspace
* Check on initial script running okay 
* Can workspaces be re-populated with updated scripts if bugs are found

## Workshop is Record
* Get stuck can always come back later
* 

## Outline
- Introduction
  -  Set up of all the packages 
- ADSL (@bms63 )
  -  Spec introduction
  - Using metacore/metatools to do numeric
  - Running all functions/code
  - We need to select a few to go into detail about 
  - xportr to create the xpt
- Break for 5 minutes
- ADVS (@Fanny-Gautier )
  - Need to develop spec for ADVS
  - Spec introduction
  - Using metacore/metatools to do numeric, etc
  - Running all functions/code
  - We need to select a few to go into detail about 
  - xportr to create the xpt
- Brief intro to extension packages

# Todos

- [ ]  Set up excel file with ADSL, ADVS - Phuse MS Teams (@bms63)
- [ ] Populate ADVS (@Fanny-Gautier)
- [ ] Agenda for the website slides (@bms63)

**Comment by bms63** [comment]
## September 16th 2024

## Some notes

* Issues with differences in SDTM IG.  Need to state what IGs we are using
* Specs between companies are very different - whoa
* Sticking with P21 Specs - clean up ADSL and leave ADLB as an example
* We need to be prepared for folks to fixate on the specs, but we don't want to focus on this - the workshop is really for admiral

## To Ponder
* How much do we use metacore/metatools?  I was just thinking for numeric variables, dropping variables, labels, and using xportr for lengths, types, etc.  Keep super simple!!
* How much do we present on admiralpeds?
* What slides to we produce versus exercises?
* How does someone get the exercises and work on them?
* How does someone get the solutions if they get stuck?

## Actions
- [ ] @bms63 to clean up ADSL in specs
- [ ] @bms63 get ADSL working with code and specs

**Comment by bms63** [comment]
@manciniedoardo and @Fanny-Gautier - some minor notes.  Feel free to drop thoughts, concerns, etc in here
